#!/bin/bash

# Script to copy logo from assets to public after generation
# This ensures the logo is available for the PWA manifest

SOURCE_DIR="src/assets/logo"
PUBLIC_DIR="public"

if [ ! -d "$SOURCE_DIR" ]; then
  echo "Logo directory not found: $SOURCE_DIR"
  exit 1
fi

# Check if logo files exist in public (generated by generate-logo-sizes.sh)
if [ -f "$PUBLIC_DIR/logo-512x512.png" ]; then
  echo "✅ Logo files already exist in public directory"
  echo "Files found:"
  ls -lh $PUBLIC_DIR/logo-*.png 2>/dev/null || echo "No logo-*.png files found"
else
  echo "⚠️  Logo files not found in public directory"
  echo "Please run: ./scripts/generate-logo-sizes.sh first"
  exit 1
fi

echo ""
echo "Logo setup complete! The following files should be available:"
echo "- logo-16x16.png"
echo "- logo-32x32.png"
echo "- logo-96x96.png"
echo "- logo-152x152.png"
echo "- logo-167x167.png"
echo "- logo-180x180.png"
echo "- logo-192x192.png"
echo "- logo-256x256.png"
echo "- logo-512x512.png"
